[package]
name = "carina-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "carina"
path = "src/main.rs"

[dependencies]
carina-core = { path = "../carina-core" }
carina-provider-aws = { path = "../carina-provider-aws" }
carina-provider-awscc = { path = "../carina-provider-awscc" }
carina-state = { path = "../carina-state" }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
colored = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = "2"
uuid = { version = "1", features = ["v4"] }
